[tool.poetry]
name = "soca"
version = "0.1.0"
description = ""
authors = ["Muhammad Naufal <me@falkia34.dev>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.13.3"
fastapi = "0.115.12"
uvicorn = { extras = ["standard"], version = "0.34.2" }
pydantic-settings = "2.9.1"
opencv-python = "^4.8.1.78"
vidgear = "0.3.3"
yt-dlp = "2024.12.23"
orjson = "3.10.18"
python-dotenv = "1.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
