[tool.poetry]
name = "soca"
version = "0.1.0"
description = ""
authors = ["Muhammad Naufal <me@falkia34.dev>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.14.2"
fastapi = "0.125.0"
uvicorn = { extras = ["standard"], version = "0.38.0" }
pydantic-settings = "2.12.0"
opencv-python = "^4.8.1.78"
vidgear = "0.3.4"
yt-dlp = "2024.12.23"
orjson = "3.11.5"
python-dotenv = "1.2.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
